### ISSUE TITLE
Unable to install to SFDC Org

### ISSUE THREAD

**Issue by MattGHarvey** [mailtoharshit/PolyForce#1]
When trying to install the package into an org, we're getting a "The AppExchange package has been deprecated and can no longer be installed" error/message. Can this be fixed?

**Comment by mailtoharshit** [comment]
Check out for new link in readme now

**Comment by mailtoharshit** [comment]
Thanks for addressing this

**Comment by MattGHarvey** [comment]
Thanks for fixing this...I didn't want to have to manually create the
components!

**Comment by mailtoharshit** [comment]
Fixed
